version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: alan
      POSTGRES_PASSWORD: P@ss1234
      POSTGRES_DB: chatroom
    ports:
      - "5422:5422"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
